version: '3'

services:

    redundant-db:
        image: mysql/mysql-server:latest
        container_name: database
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}"
            - "MYSQL_DATABASE=${DATABASE_NAME}"
            - "MYSQL_USER=${DATABASE_USERNAME}"
            - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
        networks:
            - internal
        volumes:
            - redundant-db:/var/lib/mysql

    openvino-client:
        build: .
        container_name: openvino-client
        privileged: true
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        environment:
            - "DATABASE_HOST=database"
            - "DATABASE_PORT=3306"
            - "DATABASE_DIALECT=mysql"
            - "DATABASE_NAME=${DATABASE_NAME}"
            - "DATABASE_CHARSET=${DATABASE_CHARSET}"
            - "DATABASE_USERNAME=${DATABASE_USERNAME}"
            - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
        networks:
            - internal

networks:
    internal:
                 
volumes:
    redundant-database:
