version: '3'

services:

    redundant-db:
        image: biarms/mysql:latest
        container_name: database
        restart: unless-stopped
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}"
            - "MYSQL_DATABASE=${DATABASE_NAME}"
            - "MYSQL_USER=${DATABASE_USERNAME}"
            - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
        networks:
            - internal
        volumes:
            - redundant-db:/var/lib/mysql
            
    openvino-client:
        build: .
        container_name: openvino-client
        restart: unless-stopped
        privileged: true
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
            - "/dev/gpiomem:/dev/gpiomem"
            - "/dev/i2c-1:/dev/i2c-1"
        environment:
            - "DATABASE_HOST=${DATABASE_HOST}"
            - "DATABASE_PORT=${DATABASE_PORT}"
            - "DATABASE_DIALECT=mysql"
            - "DATABASE_NAME=${DATABASE_NAME}"
            - "DATABASE_CHARSET=${DATABASE_CHARSET}"
            - "DATABASE_USERNAME=${DATABASE_USERNAME}"
            - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
            - "API_ENDPOINT=${API_ENDPOINT}"
            - "BLOOCK_APIKEY=${BLOOCK_APIKEY}"
        networks:
            - internal

networks:
    internal:
                 
volumes:
    redundant-db:
